# bar on the top of the windows
set-option -g default-terminal "screen-256color"
set-option -g status-position top
set-option -g status-bg cyan


# change prefix key from CTRL+B to ALT+A
unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

# set
set -g mouse on

# vim mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind P paste-buffer
setw -g mode-keys vi

# copy to system clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
